### ISSUE TITLE
Add Keywords in a Meta Tag 

### ISSUE THREAD

**Issue by PatrickFrankAIU** [PatrickFrankAIU/LunarSparkle2403A#16]
- [ ] Create a meta tag in each page's head element (add to the example below and remove the "..." periods)
- [ ] Add keywords to document the content of that page
- [ ] Instructor approval, commit, and sync

Example:

```
<meta name="description" content="Lunar Sparkle Jewelry offers... . Explore our collection of.... Find a perfect....">
    <meta name="keywords" content="Jewelry, Lunar Sparkle, .... ">
```

**Comment by PatrickFrankAIU** [comment]
Background: Even though Google doesn't use them for Search results anymore, there are still good reasons to use Meta tags. Here are some: 

**Improved Click-Through Rates (CTR):** Meta descriptions, though not used for ranking, appear in search engine results pages (SERPs). A well-crafted meta description can attract users to click on your link, improving CTR.

**Social Media Sharing:** Meta tags, particularly Open Graph tags (for Facebook) and Twitter Cards, control how your content is displayed when shared on social media. This can enhance visibility and engagement.

**Browser Behavior:** Some meta tags, like viewport for responsive design, control how browsers display your content, ensuring a better user experience on different devices.

**Search Engines Beyond Google:** Other search engines and directory sites might still use meta tags for indexing and ranking purposes.

**Accessibility and Usability:** Meta tags like charset and author provide essential information that can improve the accessibility and usability of your website.

**Verification and Ownership:** Meta tags are often used for site verification and to claim ownership in various webmaster tools and services, such as Google Search Console and Bing Webmaster Tools.

**SEO Best Practices:** Even if meta tags don't directly impact rankings, they are part of good SEO practices and contribute to overall site health and performance.
